version: '3.7'

services:
    db:
        container_name: course-db
        image: postgres:latest
        restart: always
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: admin
            POSTGRES_DB: course-db
        ports: 
            - 5560:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@course.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    pgdata:
    pgadmin-data:
    